/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ClassroomClassroomIdImport } from './routes/classroom/$classroomId'
import { Route as ClassroomEditClassroomEditClassroomIdImport } from './routes/classroom_/editClassroom/$editClassroomId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ClassroomClassroomIdRoute = ClassroomClassroomIdImport.update({
  id: '/classroom/$classroomId',
  path: '/classroom/$classroomId',
  getParentRoute: () => rootRoute,
} as any)

const ClassroomEditClassroomEditClassroomIdRoute =
  ClassroomEditClassroomEditClassroomIdImport.update({
    id: '/classroom_/editClassroom/$editClassroomId',
    path: '/classroom/editClassroom/$editClassroomId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/classroom/$classroomId': {
      id: '/classroom/$classroomId'
      path: '/classroom/$classroomId'
      fullPath: '/classroom/$classroomId'
      preLoaderRoute: typeof ClassroomClassroomIdImport
      parentRoute: typeof rootRoute
    }
    '/classroom_/editClassroom/$editClassroomId': {
      id: '/classroom_/editClassroom/$editClassroomId'
      path: '/classroom/editClassroom/$editClassroomId'
      fullPath: '/classroom/editClassroom/$editClassroomId'
      preLoaderRoute: typeof ClassroomEditClassroomEditClassroomIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classroom/$classroomId': typeof ClassroomClassroomIdRoute
  '/classroom/editClassroom/$editClassroomId': typeof ClassroomEditClassroomEditClassroomIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classroom/$classroomId': typeof ClassroomClassroomIdRoute
  '/classroom/editClassroom/$editClassroomId': typeof ClassroomEditClassroomEditClassroomIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classroom/$classroomId': typeof ClassroomClassroomIdRoute
  '/classroom_/editClassroom/$editClassroomId': typeof ClassroomEditClassroomEditClassroomIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/classroom/$classroomId'
    | '/classroom/editClassroom/$editClassroomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/classroom/$classroomId'
    | '/classroom/editClassroom/$editClassroomId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/classroom/$classroomId'
    | '/classroom_/editClassroom/$editClassroomId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClassroomClassroomIdRoute: typeof ClassroomClassroomIdRoute
  ClassroomEditClassroomEditClassroomIdRoute: typeof ClassroomEditClassroomEditClassroomIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClassroomClassroomIdRoute: ClassroomClassroomIdRoute,
  ClassroomEditClassroomEditClassroomIdRoute:
    ClassroomEditClassroomEditClassroomIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/classroom/$classroomId",
        "/classroom_/editClassroom/$editClassroomId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/classroom/$classroomId": {
      "filePath": "classroom/$classroomId.tsx"
    },
    "/classroom_/editClassroom/$editClassroomId": {
      "filePath": "classroom_/editClassroom/$editClassroomId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
