/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninupImport } from './routes/signinup'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsMenuImport } from './routes/settings/menu'
import { Route as ClassroomNewmdImport } from './routes/classroom/newmd'
import { Route as ClassroomClassroomIdImport } from './routes/classroom/$classroomId'
import { Route as ClassroomEditEditClassroomIdImport } from './routes/classroom_/edit/$editClassroomId'

// Create/Update Routes

const SigninupRoute = SigninupImport.update({
  id: '/signinup',
  path: '/signinup',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsMenuRoute = SettingsMenuImport.update({
  id: '/settings/menu',
  path: '/settings/menu',
  getParentRoute: () => rootRoute,
} as any)

const ClassroomNewmdRoute = ClassroomNewmdImport.update({
  id: '/classroom/newmd',
  path: '/classroom/newmd',
  getParentRoute: () => rootRoute,
} as any)

const ClassroomClassroomIdRoute = ClassroomClassroomIdImport.update({
  id: '/classroom/$classroomId',
  path: '/classroom/$classroomId',
  getParentRoute: () => rootRoute,
} as any)

const ClassroomEditEditClassroomIdRoute =
  ClassroomEditEditClassroomIdImport.update({
    id: '/classroom_/edit/$editClassroomId',
    path: '/classroom/edit/$editClassroomId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/signinup': {
      id: '/signinup'
      path: '/signinup'
      fullPath: '/signinup'
      preLoaderRoute: typeof SigninupImport
      parentRoute: typeof rootRoute
    }
    '/classroom/$classroomId': {
      id: '/classroom/$classroomId'
      path: '/classroom/$classroomId'
      fullPath: '/classroom/$classroomId'
      preLoaderRoute: typeof ClassroomClassroomIdImport
      parentRoute: typeof rootRoute
    }
    '/classroom/newmd': {
      id: '/classroom/newmd'
      path: '/classroom/newmd'
      fullPath: '/classroom/newmd'
      preLoaderRoute: typeof ClassroomNewmdImport
      parentRoute: typeof rootRoute
    }
    '/settings/menu': {
      id: '/settings/menu'
      path: '/settings/menu'
      fullPath: '/settings/menu'
      preLoaderRoute: typeof SettingsMenuImport
      parentRoute: typeof rootRoute
    }
    '/classroom_/edit/$editClassroomId': {
      id: '/classroom_/edit/$editClassroomId'
      path: '/classroom/edit/$editClassroomId'
      fullPath: '/classroom/edit/$editClassroomId'
      preLoaderRoute: typeof ClassroomEditEditClassroomIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/signinup': typeof SigninupRoute
  '/classroom/$classroomId': typeof ClassroomClassroomIdRoute
  '/classroom/newmd': typeof ClassroomNewmdRoute
  '/settings/menu': typeof SettingsMenuRoute
  '/classroom/edit/$editClassroomId': typeof ClassroomEditEditClassroomIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/signinup': typeof SigninupRoute
  '/classroom/$classroomId': typeof ClassroomClassroomIdRoute
  '/classroom/newmd': typeof ClassroomNewmdRoute
  '/settings/menu': typeof SettingsMenuRoute
  '/classroom/edit/$editClassroomId': typeof ClassroomEditEditClassroomIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/signinup': typeof SigninupRoute
  '/classroom/$classroomId': typeof ClassroomClassroomIdRoute
  '/classroom/newmd': typeof ClassroomNewmdRoute
  '/settings/menu': typeof SettingsMenuRoute
  '/classroom_/edit/$editClassroomId': typeof ClassroomEditEditClassroomIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/signinup'
    | '/classroom/$classroomId'
    | '/classroom/newmd'
    | '/settings/menu'
    | '/classroom/edit/$editClassroomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/signinup'
    | '/classroom/$classroomId'
    | '/classroom/newmd'
    | '/settings/menu'
    | '/classroom/edit/$editClassroomId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/signinup'
    | '/classroom/$classroomId'
    | '/classroom/newmd'
    | '/settings/menu'
    | '/classroom_/edit/$editClassroomId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SigninupRoute: typeof SigninupRoute
  ClassroomClassroomIdRoute: typeof ClassroomClassroomIdRoute
  ClassroomNewmdRoute: typeof ClassroomNewmdRoute
  SettingsMenuRoute: typeof SettingsMenuRoute
  ClassroomEditEditClassroomIdRoute: typeof ClassroomEditEditClassroomIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SigninupRoute: SigninupRoute,
  ClassroomClassroomIdRoute: ClassroomClassroomIdRoute,
  ClassroomNewmdRoute: ClassroomNewmdRoute,
  SettingsMenuRoute: SettingsMenuRoute,
  ClassroomEditEditClassroomIdRoute: ClassroomEditEditClassroomIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/signinup",
        "/classroom/$classroomId",
        "/classroom/newmd",
        "/settings/menu",
        "/classroom_/edit/$editClassroomId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/signinup": {
      "filePath": "signinup.tsx"
    },
    "/classroom/$classroomId": {
      "filePath": "classroom/$classroomId.tsx"
    },
    "/classroom/newmd": {
      "filePath": "classroom/newmd.tsx"
    },
    "/settings/menu": {
      "filePath": "settings/menu.tsx"
    },
    "/classroom_/edit/$editClassroomId": {
      "filePath": "classroom_/edit/$editClassroomId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
